import type { AccordDefinition, AccordId } from '../model';

export const ACCORD_DEFINITIONS = [
  {
    id: 'accord_ashline_clean_corridor',
    factionId: 'faction_ashline_bureau',
    label: 'Clean Corridor',
    description: 'Use official corridors to suppress Heat while Ashline writes more of you down.',
    durationWeeks: 2,
    cost: { resources: 700 },
    immediateEffects: { heat: -6 },
    weeklyEffects: { heat: -3 },
    factionEffectsOnStart: { standing: 3, suspicion: 8, obligation: 8 },
    factionEffectsPerWeek: { suspicion: 3 },
    tags: ['heat_control', 'security'],
  },
  {
    id: 'accord_ashline_inspection_delay',
    factionId: 'faction_ashline_bureau',
    label: 'Inspection Delay',
    description: 'Make an exposed Front disappear from the inspection route for one clean window.',
    durationWeeks: 2,
    requirements: [{ metric: 'standing', gte: 35 }, { type: 'owned_front_required' }],
    cost: { intel: 4 },
    immediateEffects: { heat: -3 },
    weeklyEffects: {},
    factionEffectsOnStart: { standing: -2, suspicion: 6, obligation: 10 },
    frontEffectsOnStart: [{ type: 'cool_highest_exposure_front', exposureDelta: -10 }],
    tags: ['fronts', 'security', 'heat_control'],
  },
  {
    id: 'accord_helix_quiet_capital',
    factionId: 'faction_helix_meridian',
    label: 'Quiet Capital',
    description: 'Let Helix fund the next move through accounts that will ask for you later.',
    durationWeeks: 2,
    immediateEffects: { resources: 1600, heat: 2 },
    weeklyEffects: { resources: 250 },
    factionEffectsOnStart: { standing: 2, suspicion: 4, obligation: 16 },
    ledgerEffectsOnStart: [
      {
        type: 'create',
        definitionId: 'debt_dirty_books',
        relatedFactionId: 'faction_helix_meridian',
      },
    ],
    tags: ['resources', 'fronts', 'ledger'],
  },
  {
    id: 'accord_helix_permit_shell',
    factionId: 'faction_helix_meridian',
    label: 'Permit Shell',
    description: 'Wrap your infrastructure in paperwork that looks legitimate from a distance.',
    durationWeeks: 3,
    cost: { resources: 600 },
    immediateEffects: { heat: -2 },
    weeklyEffects: { resources: 150 },
    factionEffectsOnStart: { standing: 4, suspicion: 5, obligation: 8 },
    tags: ['fronts', 'resources', 'security'],
  },
  {
    id: 'accord_velvet_guest_list',
    factionId: 'faction_velvet_house',
    label: 'Guest List Pact',
    description: 'Trade favors with Velvet House for rooms, names, and a faster claim on the Ward.',
    durationWeeks: 2,
    cost: { resources: 500 },
    immediateEffects: { intel: 5, dominion: 2 },
    weeklyEffects: { intel: 2, dominion: 1 },
    factionEffectsOnStart: { standing: 5, suspicion: 3, obligation: 10 },
    rivalPressureEffectsOnStart: { rival_nyx_ardent: 5 },
    tags: ['nightlife', 'intel', 'dominion', 'rival_pressure'],
  },
  {
    id: 'accord_velvet_silence',
    factionId: 'faction_velvet_house',
    label: 'Velvet Silence',
    description: 'Let Velvet House soften testimony before panic becomes a public language.',
    durationWeeks: 2,
    requirements: [{ metric: 'standing', gte: 45 }],
    cost: { intel: 5 },
    immediateEffects: { heat: -5, loyalty: 3 },
    weeklyEffects: { loyalty: 1 },
    factionEffectsOnStart: { standing: -2, obligation: 8, suspicion: 4 },
    tags: ['nightlife', 'heat_control', 'stability'],
  },
  {
    id: 'accord_chrome_dockside_tithe',
    factionId: 'faction_chrome_maw',
    label: 'Dockside Tithe',
    description: 'Take Chrome Maw money from the docks and accept that everyone hears it move.',
    durationWeeks: 2,
    immediateEffects: { resources: 1000, dominion: 3, heat: 4 },
    weeklyEffects: { resources: 500, heat: 2 },
    factionEffectsOnStart: { standing: 3, suspicion: 5, obligation: 12 },
    rivalPressureEffectsOnStart: { rival_knox_marrow: 4 },
    tags: ['resources', 'dominion', 'industrial', 'rival_pressure'],
  },
  {
    id: 'accord_chrome_muscle_retainer',
    factionId: 'faction_chrome_maw',
    label: 'Muscle on Retainer',
    description: 'Put Chrome Maw muscle on your side long enough to make Dominion visible.',
    durationWeeks: 2,
    cost: { resources: 600 },
    immediateEffects: { dominion: 6, loyalty: -2, heat: 5 },
    weeklyEffects: { dominion: 1, heat: 1 },
    factionEffectsOnStart: { standing: 4, suspicion: 8, obligation: 8 },
    tags: ['dominion', 'resources', 'industrial'],
  },
  {
    id: 'accord_ghostline_dead_channel',
    factionId: 'faction_ghostline_communion',
    label: 'Dead Channel Access',
    description: 'Open a dead relay for intelligence that arrives with something still attached.',
    durationWeeks: 2,
    cost: { resources: 400 },
    immediateEffects: { intel: 8, ruin: 3 },
    weeklyEffects: { intel: 3, ruin: 1 },
    factionEffectsOnStart: { standing: 4, suspicion: 2, obligation: 10 },
    ledgerEffectsOnStart: [
      {
        type: 'create',
        definitionId: 'secret_dead_channel_trace',
        relatedFactionId: 'faction_ghostline_communion',
      },
    ],
    tags: ['intel', 'ledger', 'weird', 'ruin'],
  },
  {
    id: 'accord_ghostline_mercy_static',
    factionId: 'faction_ghostline_communion',
    label: 'Mercy of Static',
    description: 'Let Ghostline Communion scrub rot from the signal and leave Heat in its place.',
    durationWeeks: 2,
    requirements: [{ metric: 'standing', gte: 40 }],
    cost: { intel: 5 },
    immediateEffects: { ruin: -4, heat: 2 },
    weeklyEffects: { ruin: -1 },
    factionEffectsOnStart: { standing: -3, obligation: 12, suspicion: 3 },
    tags: ['ruin', 'weird', 'stability'],
  },
] as const satisfies readonly AccordDefinition[];

export function getAccordDefinition(accordId: AccordId): AccordDefinition | undefined {
  return ACCORD_DEFINITIONS.find((accord) => accord.id === accordId);
}
