import type { Operative, RecruitCandidate } from '../model';

export const DISTRICT_ZERO_STARTING_OPERATIVES: readonly Operative[] = [
  {
    id: 'op_mara_voss',
    name: 'Mara Voss',
    archetype: 'Infiltrator',
    loyalty: 72,
    stress: 18,
    violence: 35,
    charm: 58,
    tech: 45,
    subtlety: 82,
    traitIds: ['ghost_debt', 'clean_entry'],
    status: 'available',
  },
  {
    id: 'op_juno_hex',
    name: 'Juno Hex',
    archetype: 'Ghost Hacker',
    loyalty: 61,
    stress: 32,
    violence: 20,
    charm: 35,
    tech: 90,
    subtlety: 55,
    traitIds: ['brilliant_unstable', 'ghost_touch'],
    status: 'available',
  },
  {
    id: 'op_saint_calder',
    name: 'Saint Calder',
    archetype: 'Fixer',
    loyalty: 66,
    stress: 20,
    violence: 45,
    charm: 78,
    tech: 35,
    subtlety: 62,
    traitIds: ['silver_tongue', 'probably_lying'],
    status: 'available',
  },
] as const;

export const DISTRICT_ZERO_RECRUIT_POOL: readonly RecruitCandidate[] = [
  {
    id: 'op_iris_vale',
    name: 'Iris Vale',
    archetype: 'Socialite',
    violence: 15,
    charm: 88,
    tech: 30,
    subtlety: 68,
    traitIds: ['velvet_access'],
  },
  {
    id: 'op_knox_riven',
    name: 'Knox Riven',
    archetype: 'Enforcer',
    violence: 86,
    charm: 25,
    tech: 20,
    subtlety: 38,
    traitIds: ['loud_solution'],
  },
  {
    id: 'op_orchid_seven',
    name: 'Orchid Seven',
    archetype: 'Courier',
    violence: 30,
    charm: 52,
    tech: 50,
    subtlety: 78,
    traitIds: ['knows_the_routes'],
  },
] as const;

