import type { ActionDefinition, ActionId } from '../model';

export const DISTRICT_ZERO_ACTIONS: readonly ActionDefinition[] = [
  {
    id: 'gather_intel',
    label: 'Gather Intel',
    commandCost: 1,
    resourceCost: 400,
    effects: {
      intel: 10,
      heat: 2,
    },
    operativeSkill: 'subtlety',
    baseRisk: 10,
    stressType: 'normal',
    assignment: 'optional',
    requiresTarget: false,
    allowedTargetTypes: ['district', 'venue', 'rival'],
  },
  {
    id: 'run_small_job',
    label: 'Run a Small Job',
    commandCost: 1,
    resourceCost: 0,
    effects: {
      resources: 1500,
      dominion: 4,
      heat: 9,
      loyalty: -3,
    },
    operativeSkill: 'violence',
    baseRisk: 22,
    stressType: 'dangerous',
    assignment: 'optional',
    requiresTarget: true,
    allowedTargetTypes: ['district', 'venue'],
  },
  {
    id: 'bribe_official',
    label: 'Bribe an Official',
    commandCost: 1,
    resourceCost: 1200,
    effects: {
      heat: -12,
      intel: 2,
      ruin: 2,
    },
    operativeSkill: 'charm',
    baseRisk: 14,
    stressType: 'normal',
    assignment: 'optional',
    requiresTarget: false,
    allowedTargetTypes: ['district', 'rival'],
  },
  {
    id: 'recruit_operative',
    label: 'Recruit an Operative',
    commandCost: 1,
    resourceCost: 1600,
    effects: {
      loyalty: -4,
      dominion: 3,
    },
    baseRisk: 12,
    stressType: 'none',
    assignment: 'none',
    requiresTarget: true,
    allowedTargetTypes: ['recruit'],
  },
  {
    id: 'expand_influence',
    label: 'Expand Influence',
    commandCost: 1,
    resourceCost: 850,
    effects: {
      dominion: 9,
      heat: 8,
      loyalty: -3,
      ruin: 1,
    },
    operativeSkill: 'charm',
    baseRisk: 18,
    stressType: 'normal',
    assignment: 'optional',
    requiresTarget: true,
    allowedTargetTypes: ['district', 'venue'],
  },
  {
    id: 'lay_low',
    label: 'Lay Low',
    commandCost: 1,
    resourceCost: 100,
    effects: {
      heat: -12,
      loyalty: 5,
      dominion: -1,
    },
    baseRisk: 4,
    stressType: 'recovery',
    assignment: 'optional',
    requiresTarget: false,
    allowedTargetTypes: ['district', 'venue', 'front'],
  },
  {
    id: 'work_the_ledger',
    label: 'Work the Ledger',
    commandCost: 1,
    resourceCost: 0,
    effects: {},
    baseRisk: 0,
    stressType: 'none',
    assignment: 'none',
    requiresTarget: true,
    allowedTargetTypes: ['ledger'],
  },
  {
    id: 'manage_contact',
    label: 'Manage Contact',
    commandCost: 1,
    resourceCost: 0,
    effects: {},
    baseRisk: 10,
    stressType: 'none',
    assignment: 'none',
    requiresTarget: true,
    allowedTargetTypes: ['contact'],
  },
  {
    id: 'invest_front',
    label: 'Invest in Front',
    commandCost: 1,
    resourceCost: 0,
    effects: {},
    baseRisk: 10,
    stressType: 'none',
    assignment: 'none',
    requiresTarget: true,
    allowedTargetTypes: ['front_opportunity', 'front'],
  },
] as const;

export function getActionDefinition(actionId: ActionId): ActionDefinition | undefined {
  return DISTRICT_ZERO_ACTIONS.find((action) => action.id === actionId);
}
