import type { LedgerEntryDefinition, LedgerEntryDefinitionId } from '../model';

export const LEDGER_ENTRY_DEFINITIONS = [
  {
    id: 'secret_patrol_schedule',
    kind: 'secret',
    name: 'Patrol Schedule',
    description: 'Private security rotations through the lower avenues and sealed service decks.',
    rarity: 'common',
    tags: ['secret', 'corp', 'heat', 'security'],
    discovery: {
      targetTags: ['industrial', 'smuggling', 'violence'],
      districtIds: ['district_chrome_narrows'],
      baseWeight: 14,
    },
    useOptions: [
      {
        id: 'burn_patrol_window',
        label: 'Burn Patrol Window',
        description: 'Spend the schedule to move heat off your routes.',
        cost: { intel: 2 },
        effects: { heat: -12 },
        consumesEntry: true,
        tags: ['heat', 'security'],
      },
    ],
    repeatWeightMultiplier: 0.7,
    flavor: {
      shortLabel: 'Patrols',
      visualTags: ['routes', 'security'],
    },
  },
  {
    id: 'secret_magistrate_glass_room',
    kind: 'secret',
    name: 'Magistrate in the Glass Room',
    description: 'A corp magistrate was recorded entering a memory lounge under a false name.',
    rarity: 'uncommon',
    tags: ['secret', 'blackmail', 'corp', 'nightlife'],
    discovery: {
      targetTags: ['nightlife', 'liaison', 'memory'],
      venueIds: ['venue_glass_saint'],
      baseWeight: 10,
    },
    useOptions: [
      {
        id: 'press_the_magistrate',
        label: 'Press the Magistrate',
        description: 'Turn the recording into a clean opening with a dirty shadow.',
        effects: { dominion: 5, heat: -6, ruin: 2 },
        consumesEntry: true,
        riskModifier: 2,
        tags: ['dominion', 'heat', 'ruin'],
      },
    ],
    repeatWeightMultiplier: 0.45,
    flavor: {
      shortLabel: 'Magistrate',
      visualTags: ['blackmail', 'glass'],
    },
  },
  {
    id: 'secret_nyx_velvet_ledger',
    kind: 'secret',
    name: "Nyx's Velvet Ledger",
    description: 'A private index of names Nyx Ardent needs kept out of hostile hands.',
    rarity: 'rare',
    tags: ['secret', 'rival', 'nyx', 'social'],
    discovery: {
      targetTags: ['nightlife', 'liaison', 'social'],
      rivalIds: ['rival_nyx_ardent'],
      districtIds: ['district_violet_ward'],
      baseWeight: 6,
    },
    useOptions: [
      {
        id: 'bleed_velvet_names',
        label: 'Bleed Velvet Names',
        description: "Use Nyx's list to claim space while escalating her attention.",
        effects: { dominion: 7, loyalty: -2, ruin: 3 },
        consumesEntry: true,
        riskModifier: 4,
        tags: ['dominion', 'rival', 'ruin'],
      },
    ],
    unique: true,
    repeatWeightMultiplier: 0.2,
    flavor: {
      shortLabel: 'Velvet Ledger',
      visualTags: ['nyx', 'names'],
    },
  },
  {
    id: 'secret_knox_route_manifests',
    kind: 'secret',
    name: "Knox's Route Manifests",
    description: 'Smuggling manifests that show which Chrome Narrows routes Knox cannot lose.',
    rarity: 'uncommon',
    tags: ['secret', 'rival', 'knox', 'routes'],
    discovery: {
      targetTags: ['violence', 'smuggling', 'industrial'],
      rivalIds: ['rival_knox_marrow'],
      districtIds: ['district_chrome_narrows'],
      venueIds: ['venue_zero_mercy'],
      baseWeight: 9,
    },
    useOptions: [
      {
        id: 'reroute_knox_cargo',
        label: 'Reroute Knox Cargo',
        description: 'Steal space and cash from routes Knox thought were sealed.',
        effects: { resources: 900, dominion: 3, heat: 3 },
        consumesEntry: true,
        riskModifier: 3,
        tags: ['resources', 'dominion', 'heat'],
      },
    ],
    repeatWeightMultiplier: 0.45,
    flavor: {
      shortLabel: 'Manifests',
      visualTags: ['knox', 'routes'],
    },
  },
  {
    id: 'secret_ghostline_buyer_list',
    kind: 'secret',
    name: 'Ghostline Buyer List',
    description: 'A quiet list of buyers who paid extra to forget what they bought.',
    rarity: 'common',
    tags: ['secret', 'market', 'memory', 'money'],
    discovery: {
      targetTags: ['black_market', 'auction', 'memory', 'rare'],
      districtIds: ['district_ghostline_market'],
      venueIds: ['venue_black_halo_exchange'],
      baseWeight: 13,
    },
    useOptions: [
      {
        id: 'sell_buyer_names',
        label: 'Sell Buyer Names',
        description: 'Convert the list into fast money and a little more rot.',
        effects: { resources: 1300, intel: -2, ruin: 2 },
        consumesEntry: true,
        tags: ['resources', 'ruin'],
      },
    ],
    repeatWeightMultiplier: 0.65,
    flavor: {
      shortLabel: 'Buyer List',
      visualTags: ['ghostline', 'auction'],
    },
  },
  {
    id: 'secret_dead_channel_trace',
    kind: 'secret',
    name: 'Dead Channel Trace',
    description: 'A signal trace through a dead relay that still answers to the right ghost.',
    rarity: 'common',
    tags: ['secret', 'tech', 'intel', 'ghostline'],
    discovery: {
      targetTags: ['intel', 'memory', 'weird', 'black_market'],
      districtIds: ['district_ghostline_market'],
      baseWeight: 12,
    },
    useOptions: [
      {
        id: 'open_dead_channel',
        label: 'Open Dead Channel',
        description: 'Spend the trace for cleaner intelligence.',
        effects: { intel: 6, heat: 2 },
        relatedContactEffects: { leverage: 2, volatility: 2 },
        consumesEntry: true,
        tags: ['intel', 'heat'],
      },
    ],
    repeatWeightMultiplier: 0.7,
    flavor: {
      shortLabel: 'Dead Channel',
      visualTags: ['trace', 'relay'],
    },
  },
  {
    id: 'secret_back_room_guest_list',
    kind: 'secret',
    name: 'Back Room Guest List',
    description: 'A list of names from a private room that officially has no door.',
    rarity: 'uncommon',
    tags: ['secret', 'front', 'nightlife', 'blackmail', 'intel'],
    useOptions: [
      {
        id: 'lean_on_the_guest_list',
        label: 'Lean on the Guest List',
        description: 'Turn private appetites into visible territory.',
        cost: { intel: 3 },
        effects: { dominion: 6, heat: 2 },
        consumesEntry: true,
        riskModifier: 3,
        tags: ['dominion', 'intel', 'heat'],
      },
      {
        id: 'bury_names_in_static',
        label: 'Bury Names in Static',
        description: 'Spend the list to make several people forget where they saw you.',
        effects: { heat: -6, loyalty: -1 },
        consumesEntry: true,
        tags: ['heat', 'blackmail'],
      },
    ],
    repeatWeightMultiplier: 0.45,
    flavor: {
      shortLabel: 'Guest List',
      visualTags: ['front', 'private_room'],
    },
  },
  {
    id: 'debt_owes_liaison',
    kind: 'debt',
    name: 'Owes the Liaison',
    description: 'A favor accepted from the liaison network. They remember cleanly.',
    rarity: 'common',
    tags: ['debt', 'liaison', 'social'],
    useOptions: [
      {
        id: 'pay_in_credits',
        label: 'Pay in Credits',
        description: 'Clear the obligation with money before it turns personal.',
        cost: { resources: 900 },
        effects: { loyalty: 2 },
        relatedContactEffects: { trust: 4, volatility: -2 },
        consumesEntry: true,
        tags: ['settle', 'resources', 'loyalty'],
      },
      {
        id: 'offer_information',
        label: 'Offer Information',
        description: 'Trade useful intelligence instead of cash.',
        cost: { intel: 5 },
        effects: { heat: -2 },
        relatedContactEffects: { trust: 2, exposure: 2 },
        consumesEntry: true,
        tags: ['settle', 'intel', 'heat'],
      },
    ],
    repeatWeightMultiplier: 0.35,
    flavor: {
      shortLabel: 'Liaison Debt',
      visualTags: ['liaison', 'obligation'],
    },
  },
  {
    id: 'debt_unfunded_promise',
    kind: 'debt',
    name: 'Unfunded Promise',
    description: 'The crew accepted tomorrow as payment. Tomorrow is now watching.',
    rarity: 'common',
    tags: ['debt', 'crew', 'loyalty'],
    useOptions: [
      {
        id: 'make_the_crew_whole',
        label: 'Make the Crew Whole',
        description: 'Pay what you promised and repair the room.',
        cost: { resources: 1100 },
        effects: { loyalty: 5, ruin: -1 },
        consumesEntry: true,
        tags: ['settle', 'resources', 'loyalty'],
      },
      {
        id: 'show_them_receipts',
        label: 'Show Them Receipts',
        description: 'Spend proof that the delay bought everyone breathing room.',
        cost: { intel: 4 },
        effects: { loyalty: 2 },
        consumesEntry: true,
        tags: ['settle', 'intel', 'loyalty'],
      },
    ],
    repeatWeightMultiplier: 0.4,
    flavor: {
      shortLabel: 'Crew Promise',
      visualTags: ['crew', 'promise'],
    },
  },
  {
    id: 'debt_contaminated_money',
    kind: 'debt',
    name: 'Contaminated Money',
    description: 'Cash that arrived too clean, too fast, and from the wrong dead account.',
    rarity: 'uncommon',
    tags: ['debt', 'money', 'corp', 'trace'],
    useOptions: [
      {
        id: 'launder_the_stack',
        label: 'Launder the Stack',
        description: 'Pay handlers to scrub the money before it points back at you.',
        cost: { resources: 1200 },
        effects: { heat: -5, ruin: -1 },
        relatedContactEffects: { trust: 3, volatility: -3 },
        consumesEntry: true,
        tags: ['settle', 'resources', 'heat'],
      },
      {
        id: 'burn_the_trail',
        label: 'Burn the Trail',
        description: 'Spend Intel to cut the channel instead of paying professionals.',
        cost: { intel: 6 },
        effects: { heat: -7, loyalty: -1 },
        relatedContactEffects: { trust: -2, leverage: 2 },
        consumesEntry: true,
        tags: ['settle', 'intel', 'heat'],
      },
    ],
    repeatWeightMultiplier: 0.3,
    flavor: {
      shortLabel: 'Dirty Cash',
      visualTags: ['money', 'trace'],
    },
  },
  {
    id: 'debt_saints_payment_trail',
    kind: 'debt',
    name: "Saint's Payment Trail",
    description: 'A concealed Saint Calder payment trail with too many names attached.',
    rarity: 'uncommon',
    tags: ['debt', 'operative', 'saint', 'payment'],
    useOptions: [
      {
        id: 'close_saints_books',
        label: "Close Saint's Books",
        description: 'Spend money to make the paper trail boring.',
        cost: { resources: 1000 },
        effects: { heat: -4, loyalty: 1 },
        consumesEntry: true,
        tags: ['settle', 'resources', 'heat'],
      },
      {
        id: 'redirect_the_audit',
        label: 'Redirect the Audit',
        description: 'Use Intel to point the inquiry somewhere less useful.',
        cost: { intel: 5 },
        effects: { heat: -3, ruin: 1 },
        consumesEntry: true,
        tags: ['settle', 'intel', 'ruin'],
      },
    ],
    repeatWeightMultiplier: 0.35,
    flavor: {
      shortLabel: 'Payment Trail',
      visualTags: ['saint', 'ledger'],
    },
  },
  {
    id: 'debt_dirty_books',
    kind: 'debt',
    name: 'Dirty Books',
    description: 'Accounting irregularities useful today and poisonous tomorrow.',
    rarity: 'uncommon',
    tags: ['debt', 'front', 'money', 'ledger', 'heat'],
    useOptions: [
      {
        id: 'pay_auditors_off',
        label: 'Pay Auditors Off',
        description: 'Spend clean money to make the dirty books boring.',
        cost: { resources: 1200 },
        effects: { heat: -5, ruin: -1 },
        consumesEntry: true,
        tags: ['settle', 'resources', 'heat'],
      },
      {
        id: 'bury_the_trail',
        label: 'Bury the Trail',
        description: 'Use Intel to redirect the paper trail before it points home.',
        cost: { intel: 5 },
        effects: { heat: -4, loyalty: 1 },
        consumesEntry: true,
        tags: ['settle', 'intel', 'heat'],
      },
    ],
    repeatWeightMultiplier: 0.35,
    flavor: {
      shortLabel: 'Dirty Books',
      visualTags: ['front', 'books'],
    },
  },
  {
    id: 'favor_checkpoint_captain',
    kind: 'favor',
    name: 'Checkpoint Captain',
    description: 'A checkpoint captain owes you one quiet opening through a loud street.',
    rarity: 'common',
    tags: ['favor', 'heat', 'security'],
    useOptions: [
      {
        id: 'call_checkpoint',
        label: 'Call in Favor',
        description: 'Open the checkpoint and cool the immediate patrol response.',
        cost: { intel: 2 },
        effects: { heat: -10 },
        relatedContactEffects: { trust: -3, exposure: 3 },
        consumesEntry: true,
        tags: ['favor', 'heat'],
      },
    ],
    repeatWeightMultiplier: 0.55,
    flavor: {
      shortLabel: 'Checkpoint',
      visualTags: ['favor', 'security'],
    },
  },
  {
    id: 'favor_hidden_route',
    kind: 'favor',
    name: 'Hidden Route',
    description: 'A broker owes you a path through the Ghostline nobody admits exists.',
    rarity: 'common',
    tags: ['favor', 'route', 'ghostline'],
    useOptions: [
      {
        id: 'open_hidden_route',
        label: 'Open Hidden Route',
        description: 'Move people and evidence through a quieter channel.',
        cost: { intel: 1 },
        effects: { heat: -6, loyalty: 2 },
        consumesEntry: true,
        tags: ['favor', 'heat', 'loyalty'],
      },
    ],
    repeatWeightMultiplier: 0.55,
    flavor: {
      shortLabel: 'Hidden Route',
      visualTags: ['favor', 'route'],
    },
  },
] as const satisfies readonly LedgerEntryDefinition[];

export function getLedgerEntryDefinition(
  definitionId: LedgerEntryDefinitionId,
): LedgerEntryDefinition | undefined {
  return LEDGER_ENTRY_DEFINITIONS.find((entry) => entry.id === definitionId);
}
